spring:
  application:
    name: user-service-local
  datasource:
    username: postgres
    password: postgres
    #?stringtype=unspecified need to convert string into enum type in db
    url: jdbc:postgresql://localhost:5432/user-service?stringtype=unspecified

constants:
  secretKey: "secretKeySecretKeySecretKeySecretKeySecretKeySecretKey"
  tokenExpirationTime: 3600000

email:
  username: test
  confirmation:
    url: http://localhost:8080
    path: /api/v1/invitations/confirmInvitation